---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: aap-teamslackbot
  namespace: aap
  labels:
    team: aap
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /api/internal/is_alive
    initialDelay: 10
  readiness:
    path: /api/internal/is_ready
    initialDelay: 10
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki    
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
        - host: wss-primary.slack.com
  env:
    - name: PORT
      value: "8080"
  envFrom:
    - secret: aap-teamslackbot-secrets
